version: "3.9"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  create-product:
    build:
      context: ./BackEnd/Products/CreateProduct
    container_name: create-product
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - APP_PORT=8082
    ports:
      - "8082:8082"
    depends_on:
      - mongodb
    networks:
      - app-network

  get-products:
    build:
      context: ./BackEnd/Products/GetProducts
    container_name: get-products
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - APP_PORT=8083
    ports:
      - "8083:8083"
    depends_on:
      - mongodb
    networks:
      - app-network

  delete-product:
    build:
      context: ./BackEnd/Products/DeleteProduct
    container_name: delete-product
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - APP_PORT=8084
    ports:
      - "8084:8084"
    depends_on:
      - mongodb
    networks:
      - app-network
  
  update-product:
    build:
      context: ./BackEnd/Products/UpdateProduct
    container_name: update-product
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - APP_PORT=8085
    ports:
      - "8085:8085"
    depends_on:
      - mongodb
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
