version: "3.9"

services:
  # Microservicio para crear productos
  create-product:
    build:
      context: ./BackEnd/Domains/Products/CreateProduct
    container_name: create-product
    environment:
      - MONGO_URI=mongodb+srv://admin:1234PDistribuida@category.dloun.mongodb.net/product_db?retryWrites=true&w=majority
      - APP_PORT=8082
      - GRAPHQL_URL=http://graphql-gateway:8080/graphql  # Agregar esta línea
    ports:
      - "8082:8082"
    depends_on:
      - graphql-gateway  # Asegurar que GraphQL esté disponible antes de iniciar este servicio
    networks:
      - app-network

  # GraphQL Gateway
  graphql-gateway:
    build:
      context: ./BackEnd/Domains/GraphQL-Gateway
    container_name: graphql-gateway
    environment:
      - CATEGORY_SERVICE_URL=http://get-category-by-id:80/category
      - APP_PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      - get-category-by-id
    networks:
      - app-network

  # GetCategories by ID (Ahora corre en el puerto 80)
  get-category-by-id:
    build:
      context: ./BackEnd/Domains/Categories/GetCategoryById
    container_name: get-category-by-id
    environment:
      - MONGO_URI=mongodb+srv://admin:1234PDistribuida@category.dloun.mongodb.net/category_db?retryWrites=true&w=majority
      - APP_PORT=80
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
