version: '3.8'

services:
  # Microservicio de Crear Empleados
  employee-create:
    build:
      context: ./BACKEND/autentication_sprintboot
    env_file:
      - ./BACKEND/autentication_sprintboot/.env
    ports:
      - "8090:8090"
    networks:
      - app-network

  # Microservicio de Leer Empleados
  employee-read:
    build:
      context: ./BACKEND/read_employee_web
    env_file:
      - ./BACKEND/autentication_sprintboot/.env
    ports:
      - "8094:8094"
    networks:
      - app-network

  # Microservicio de Actualizar Empleados
  employee-update:
    build:
      context: ./BACKEND/springboot_update_employee
    env_file:
      - ./BACKEND/autentication_sprintboot/.env
    ports:
      - "8092:8092"
    networks:
      - app-network

  # Microservicio de Eliminar Empleados
  employee-delete:
    build:
      context: ./BACKEND/delete_employee
    env_file:
      - ./BACKEND/autentication_sprintboot/.env  
    ports:
      - "8093:8093"
    networks:
      - app-network

  # Frontend React
  frontend:
    build:
      context: ./FRONTEND/employee-app
    ports:
      - "5173:80"
    depends_on:
      - employee-create
      - employee-read
      - employee-update
      - employee-delete
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
