version: '3.8'

services:
  # Microservicio de Crear Empleados
  employee-create:
    build:
      context: ./BACKEND/autentication_sprintboot
    ports:
      - "8090:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/dboffice
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=alexander2198
    depends_on:
      - mysql-db
    networks:
      - app-network

  # Microservicio de Leer Empleados
  employee-read:
    build:
      context: ./BACKEND/read_employee_web
    ports:
      - "8094:8094"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/dboffice
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=alexander2198
    depends_on:
      - mysql-db
    networks:
      - app-network

  # Microservicio de Actualizar Empleados
  employee-update:
    build:
      context: ./BACKEND/springboot_update_employee
    ports:
      - "8092:8092"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/dboffice
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=alexander2198
    depends_on:
      - mysql-db
    networks:
      - app-network

  # Microservicio de Eliminar Empleados
  employee-delete:
    build:
      context: ./BACKEND/delete_employee
    ports:
      - "8093:8093"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/dboffice
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=alexander2198
    depends_on:
      - mysql-db
    networks:
      - app-network

  # Base de Datos MySQL
  mysql-db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: alexander2198
      MYSQL_DATABASE: dboffice
    ports:
      - "3306:3306"
    networks:
      - app-network

  # Frontend React
  frontend:
    build:
      context: ./FRONTEND/employee-app
    ports:
      - "5173:80"
    depends_on:
      - employee-create
      - employee-read
      - employee-update
      - employee-delete
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
