name: Deploy delete-category

on:
    push:
        branches:
            - Fix_Merge_Repository
        paths:
            - 'BackEnd/Domains/Categories/DeleteCategory/**'
jobs:
    # Build and Push delete-category
  build-and-push-delete:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push delete-category
        uses: docker/build-push-action@v4
        with:
          context: ./BackEnd/Domains/Categories/DeleteCategory
          file: ./BackEnd/Domains/Categories/DeleteCategory/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/delete-category:latest

    # Deploy delete-category (Depende de GraphQL y GetProductsByCategory)
  deploy-delete-category:
    needs: build-and-push-delete
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to DeleteCategory QA
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS_DELETECATEGORY_QA }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker stop delete-category || true
            sudo docker rm delete-category || true
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/delete-category:latest
            sudo docker run -d --name delete-category --network host \
              -e MONGO_URI="${{ secrets.MONGO_URI }}" \
              -e GRAPHQL_SERVICE_URL="http://${{ secrets.HOST_DNS_GRAPHQL_QA }}/graphql" \
              ${{ secrets.DOCKERHUB_USERNAME }}/delete-category:latest