name: Deploy get_ByCategory-product

on:
    push:
        branches:
            - Fix_BackEnd_GraphQL_DeleteCategory
        paths:
            - 'BackEnd/Domains/Products/GetProductsByCategory/**'
jobs:
    # Build and Push get-products-by-category
  build-and-push-get-products:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push get-products-by-category
        uses: docker/build-push-action@v4
        with:
          context: ./BackEnd/Domains/Products/GetProductsByCategory
          file: ./BackEnd/Domains/Products/GetProductsByCategory/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/get-products-by-category:latest

    # Deploy get-products-by-category
  deploy-get-products:
    needs: build-and-push-get-products
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GetProductsByCategory QA
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS_GETPRODUCTSBYCATEGORY_QA }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker stop get-products-by-category || true
            sudo docker rm get-products-by-category || true
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/get-products-by-category:latest
            sudo docker run -d --name get-products-by-category --network host \
              -e MONGO_URI="${{ secrets.MONGO_URI_PRODUCT }}" \
              -e MONGO_DBNAME="product_db" \
              -p 3001:3001 \
              ${{ secrets.DOCKERHUB_USERNAME }}/get-products-by-category:latest
