name: Deploy Login

on:
    push:
        branches:
            - Fix_Merge_Repository
        paths:
            - 'BackEnd/Domains/Employees/LoginEmployee/**'

build-and-push-loginEmployee:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21  # Asegura que sea la misma versión usada en el proyecto
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build JAR with Maven
        run: |
          cd BackEnd/Domains/Employees/LoginEmployee
          mvn clean package -DskipTests
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME2 }}
          password: ${{ secrets.DOCKERHUB_PASSWORD2 }}

      - name: Build and push login-employee
        uses: docker/build-push-action@v4
        with:
          context: ./BackEnd/Domains/Employees/LoginEmployee
          file: ./BackEnd/Domains/Employees/LoginEmployee/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME2 }}/login-employee:v1

   deploy-loginEmployee:
    needs: build-and-push-loginEmployee
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to loginEmployee QA
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS_LOGINEMPLOYEE_QA }}
          username: ${{ secrets.USERNAME2 }}
          key: ${{ secrets.EC2_SSH_KEY2 }}
          script: |
            sudo docker stop login-employee || true
            sudo docker rm login-employee || true
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME2 }}/login-employee:v1
            sudo docker run -d --name login-employee -p 8091:8091 \
              -e DB_URL="${{ secrets.DB_URL }}" \
             -e DB_USERNAME="${{ secrets.DB_USERNAME }}" \
             -e DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
              ${{ secrets.DOCKERHUB_USERNAME2 }}/login-employee:v1 