name: Deploy update-category

on:
    push:
        branches:
            - Feature_BackEnd_CategoryDomain_AddMicroservice_DeleteCategory
        paths:
            - 'BackEnd/Domains/Categories/UpdateCategory/**'
jobs:
    # Build and Push update-category
  build-and-push-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push update-category
        uses: docker/build-push-action@v4
        with:
          context: ./BackEnd/Domains/Categories/UpdateCategory
          file: ./BackEnd/Domains/Categories/UpdateCategory/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/update-category:latest

    # Deploy update-category 
  deploy-update-category:
    needs: build-and-push-update
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to UpdateCategory QA
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS_UPDATECATEGORY_QA  }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker stop update-category || true
            sudo docker rm update-category || true
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/update-category:latest
            sudo docker run -d --name update-category --network host \
              -e MONGO_URI="${{ secrets.MONGO_URI }}" \
              ${{ secrets.DOCKERHUB_USERNAME }}/update-category:latest