name: Deploy AddCart

on:
    push:
        branches:
            - Fix_Merge_Repository
        paths:
            - 'BackEnd/Domains/Cart/AddCart/**'

jobs:
    # Build and Push AddCart
  build-and-push-addcart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME2 }}
          password: ${{ secrets.DOCKERHUB_PASSWORD2 }}

      - name: Build and push AddCart
        uses: docker/build-push-action@v4
        with:
          context: ./BackEnd/Domains/Cart/AddCart
          file: ./BackEnd/Domains/Cart/AddCart/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME2 }}/add-cart:v1

    # Deploy AddCart
  deploy-addcart:
    needs: build-and-push-addcart
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to AddCart on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS_CARTSERVICE_QA }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker stop add-cart || true
            sudo docker rm add-cart || true
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME2 }}/add-cart:v1
            sudo docker run -d --name add-cart -p 8001:8001 --restart unless-stopped \
              -e MONGO_URI="${{ secrets.MONGO_URI }}" \
              -e DB_NAME="cart_db" \
              -e CART_SERVICE_URL="http://${{ secrets.HOST_DNS_ADDCART_QA }}:8001/graphql" \  # ✅ Corrección aquí
              ${{ secrets.DOCKERHUB_USERNAME2 }}/add-cart:v1 
