name: CI/CD Pipeline for Category Services

on:
  push:
    branches:
      - Test
    paths:
      - 'BackEnd/Domains/Categories/CreateCategory/**'
      - 'BackEnd/Domains/Categories/GetAllCategories/**'
      - 'BackEnd/Domains/Categories/GetCategoryById/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - { name: "create-category", path: "CreateCategory" }
          - { name: "get-all-categories", path: "GetAllCategories" }
          - { name: "get-byid-category", path: "GetCategoryById" }

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and push on Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./BackEnd/Domains/Categories/${{ matrix.service.path }}
          file: ./BackEnd/Domains/Categories/${{ matrix.service.path }}/Dockerfile
          push: true
          tags: sebastianperez02/${{ matrix.service.name }}:latest

  deploy-to-ec2:
    needs: build-and-push
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - { name: "create-category", dns: "HOST_DNS_CREATECATEGORY_QA" }
          - { name: "get-all-categories", dns: "HOST_DNS_GETALLCATEGORIES_QA" }
          - { name: "get-byid-category", dns: "HOST_DNS_GETBYIDCATEGORY_QA" }

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets[matrix.service.dns] }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker stop ${{ matrix.service.name }} || echo "No existing process found"
            sudo docker rm ${{ matrix.service.name }} || echo "No existing process found"
            sudo docker pull sebastianperez02/${{ matrix.service.name }}:latest
            sudo docker run -d -p 80:80 --name ${{ matrix.service.name }} \
              -e MONGO_URI=${{ secrets.MONGO_URI }} \
              sebastianperez02/${{ matrix.service.name }}:latest
