name: Deploy graphQL-deploy

on:
    push:
        branches:
            - Fix_Merge_Repository
        paths:
            - 'BackEnd/Domains/GraphQL-Gateway/**'

jobs:
  # Build and Push graphql-gateway
  build-and-push-graphql:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push graphql-gateway
        uses: docker/build-push-action@v4
        with:
          context: ./BackEnd/Domains/GraphQL-Gateway
          file: ./BackEnd/Domains/GraphQL-Gateway/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/graphql-gateway:latest

  # Deploy graphql-gateway
  deploy-graphql:
    needs: build-and-push-graphql
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GraphQL QA
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS_GRAPHQL_QA }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Verificar si el contenedor existe antes de detenerlo
            if [ "$(sudo docker ps -q -f name=graphql-gateway)" ]; then
                sudo docker stop graphql-gateway
                sudo docker rm graphql-gateway
            fi

            # Descargar la última imagen desde DockerHub
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/graphql-gateway:latest

            # Ejecutar el contenedor con las variables de entorno necesarias
            sudo docker run -d --name graphql-gateway --network host \
              -e CATEGORY_SERVICE_URL="http://${{ secrets.HOST_DNS_GETBYIDCATEGORY_QA }}/category" \
              -e PRODUCT_SERVICE_URL="http://${{ secrets.HOST_DNS_GETPRODUCTSBYCATEGORY_QA }}/products/by-category" \
              -e GET_PRODUCT_BY_ID_SERVICE_URL="http://${{ secrets.HOST_DNS_GETPRODUCTBYID_QA }}/products/by-id" \
              -e ADD_PRODUCT_TO_CART_SERVICE_URL="http://${{ secrets.HOST_DNS_ADDTOCART_QA }}/cart/add" \
              -e GRAPHQL_GATEWAY_URL="http://${{ secrets.HOST_DNS_GRAPHQL_QA }}/graphql" \
              ${{ secrets.DOCKERHUB_USERNAME }}/graphql-gateway:latest
