name: CI/CD Pipeline for Category Services

on:
  push:
    branches:
      - Feature_CategoryDomain_GetAllCategories
    paths:
      - 'BackEnd/Domains/Categories/CreateCategory/**'
      - 'BackEnd/Domains/Categories/GetAllCategories/**'
      - 'BackEnd/Domains/Categories/GetCategoryById/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: 
          - { name: "category-create", path: "CreateCategory" }
          - { name: "category-get-all", path: "GetAllCategories" }
          - { name: "category-get-by-id", path: "GetCategoryById" }

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image for ${{ matrix.service.name }}
        run: |
          cd BackEnd/Domains/Categories/${{ matrix.service.path }}
          docker build -t sebastianperez02/${{ matrix.service.name }} .

      - name: Push Docker image to DockerHub
        run: docker push sebastianperez02/${{ matrix.service.name }}:latest

  deploy-to-ec2:
    needs: build-and-push
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: 
          - { name: "category-create", secret: "HOST_DNS_CREATECATEGORY_QA" }
          - { name: "category-get-all", secret: "HOST_DNS_GETALLCATEGORIES_QA" }
          - { name: "category-get-by-id", secret: "HOST_DNS_GETBYIDCATEGORY_QA" }

    steps:
      - name: Set host variable
        run: echo "HOST_DNS=${{ secrets[matrix.service.secret] }}" >> $GITHUB_ENV

      - name: Deploy ${{ matrix.service.name }} to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo apt update -y
            sudo apt install -y docker.io
            sudo systemctl start docker
            sudo systemctl enable docker
            sudo usermod -aG docker $USER
            sudo chmod 666 /var/run/docker.sock

            docker pull sebastianperez02/${{ matrix.service.name }}:latest
            docker stop ${{ matrix.service.name }} || true
            docker rm ${{ matrix.service.name }} || true
            docker run -d --name ${{ matrix.service.name }} --network host \
              -e MONGO_URI="${{ secrets.MONGO_URI }}" \
              sebastianperez02/${{ matrix.service.name }}:latest
