deploy-to-ec2:
  needs: build-and-push
  runs-on: ubuntu-latest

  steps:
    - name: Deploy to CreateCategory QA
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_DNS_CREATECATEGORY_QA }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          sudo apt update -y
          sudo apt install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker
          sudo usermod -aG docker $USER
          sudo chmod 666 /var/run/docker.sock
          
          docker pull sebastianperez02/categories-app:latest
          docker stop category-service || true
          docker rm category-service || true
          docker run -d --name category-service --network host \
            -e MONGO_URI="${{ secrets.MONGO_URI }}" \
            sebastianperez02/categories-app:latest
          
          echo "Deployed CreateCategory in QA"

    - name: Deploy to GetAllCategories QA
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_DNS_GETALLCATEGORIES_QA }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          sudo apt update -y
          sudo apt install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker
          sudo usermod -aG docker $USER
          sudo chmod 666 /var/run/docker.sock
          
          docker pull sebastianperez02/categories-app:latest
          docker stop category-service || true
          docker rm category-service || true
          docker run -d --name category-service --network host \
            -e MONGO_URI="${{ secrets.MONGO_URI }}" \
            sebastianperez02/categories-app:latest
          
          echo "Deployed GetAllCategories in QA"

    - name: Deploy to GetByIDCategory QA
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_DNS_GETBYIDCATEGORY_QA }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          sudo apt update -y
          sudo apt install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker
          sudo usermod -aG docker $USER
          sudo chmod 666 /var/run/docker.sock
          
          docker pull sebastianperez02/categories-app:latest
          docker stop category-service || true
          docker rm category-service || true
          docker run -d --name category-service --network host \
            -e MONGO_URI="${{ secrets.MONGO_URI }}" \
            sebastianperez02/categories-app:latest
          
          echo "Deployed GetByIDCategory in QA"
